""" Events generated by a scene update. """

from collections import defaultdict


class UpdateEvents(object):
    """ A list of events generated by a scene update. """

    def __init__(self):
        self.events = defaultdict(list)

    def add_event(self, event):
        self.events[event.resource].append(event)

    def apply_events(self, game):
        for resource_name, events in self.events.iteritems():
            resource = game.resources[resource_name]
            for ev in events:
                resource.apply_event(ev)


class UpdateEvent(object):
    """ An event which can be applied to the named resource. """
    resource = '__undefined__'
